run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - tmp

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocritic
    - gosec
    - unconvert
    - unparam
    - bodyclose
    - noctx
    - sqlclosecheck

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true
  
  govet:
    enable-all: true
  
  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: true
  
  gosec:
    excludes:
      - G404  # Use of weak random number generator - OK for non-crypto use

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam
      - rangeValCopy

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - dupl
    - path: cmd/server/main.go
      linters:
        - errcheck
  max-same-issues: 0
  max-issues-per-linter: 0

output:
  sort-results: true
