// Code generated by mockery v2.53.6. DO NOT EDIT.

package port

import (
	context "context"

	domain "github.com/podanypepa/wbrestapi/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockSaveUserExecutor is an autogenerated mock type for the SaveUserExecutor type
type MockSaveUserExecutor struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, user
func (_m *MockSaveUserExecutor) Execute(ctx context.Context, user *domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockSaveUserExecutor creates a new instance of MockSaveUserExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSaveUserExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSaveUserExecutor {
	mock := &MockSaveUserExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
